# Generated by Django 4.2.6 on 2023-10-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=50, null=True)),
                ('reg_num', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('surname', models.CharField(max_length=50, null=True)),
                ('patronymic', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(null=True)),
                ('is_contragent', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PenalSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification_num', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('weight_list', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_feature', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductNom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('surname', models.CharField(max_length=50, null=True)),
                ('patronymic', models.CharField(max_length=50, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_num', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.car')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.driver')),
                ('specification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.penalspecification')),
            ],
        ),
        migrations.AddField(
            model_name='penalspecification',
            name='product_feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.productfeature'),
        ),
        migrations.AddField(
            model_name='penalspecification',
            name='product_nom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.productnom'),
        ),
        migrations.AddField(
            model_name='penalspecification',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ps_receiver', to='management.organization'),
        ),
        migrations.AddField(
            model_name='penalspecification',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ps_sender', to='management.organization'),
        ),
        migrations.AddField(
            model_name='penalspecification',
            name='sending_worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.worker'),
        ),
        migrations.CreateModel(
            name='AcceptanceAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_num', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('waybill_num', models.CharField(max_length=20, null=True)),
                ('waybill_weight', models.IntegerField(null=True)),
                ('in_weight', models.IntegerField(null=True)),
                ('out_weight', models.IntegerField(null=True)),
                ('penal_count', models.IntegerField(null=True)),
                ('weight_list', models.JSONField(null=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.car')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.driver')),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform', to='management.organization')),
                ('raw_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.rawmaterial')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aa_receiver', to='management.organization')),
                ('receiving_worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.worker')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aa_sender', to='management.organization')),
            ],
        ),
    ]
