# Generated by Django 4.2.6 on 2023-10-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptanceact',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='penalspecification',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
