# Generated by Django 4.2.6 on 2023-10-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_acceptanceact_status_penalspecification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
