# Generated by Django 4.2.6 on 2023-10-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_waybill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptanceact',
            name='act_num',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='penalspecification',
            name='specification_num',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='waybill_num',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
