# Generated by Django 4.2.6 on 2023-10-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_acceptanceact_act_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptanceact',
            name='waybill_num',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
