# Generated by Django 4.2.6 on 2023-12-14 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferToProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_num', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('transfer_weight', models.IntegerField(null=True)),
                ('transfer_count', models.IntegerField(null=True)),
                ('act', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.acceptanceact')),
                ('prod_executive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prod_executive', to='management.worker')),
                ('store_executive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_executive', to='management.worker')),
            ],
        ),
    ]
