# Generated by Django 4.2.6 on 2023-12-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_transfertoprod'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptanceact',
            name='bb_count',
            field=models.IntegerField(null=True),
        ),
    ]
