# Generated by Django 4.2.6 on 2023-12-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_acceptanceact_bb_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptanceact',
            old_name='bb_count',
            new_name='kip_count',
        ),
    ]
