# Generated by Django 4.2.6 on 2024-01-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_rename_bb_count_acceptanceact_kip_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalspecification',
            name='in_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='penalspecification',
            name='kip_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='penalspecification',
            name='out_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='penalspecification',
            name='penal_count',
            field=models.IntegerField(null=True),
        ),
    ]
