# Generated by Django 4.2.6 on 2024-01-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_penalspecification_in_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_metal', models.IntegerField(null=True)),
                ('color_metal', models.IntegerField(null=True)),
                ('off_color_bottle', models.IntegerField(null=True)),
                ('flex', models.IntegerField(null=True)),
                ('pss', models.IntegerField(null=True)),
                ('paper', models.IntegerField(null=True)),
                ('other', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
