# Generated by Django 4.2.6 on 2024-01-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_acceptanceact_kip_count2_acceptanceact_penal_count2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_default',
            field=models.BooleanField(null=True),
        ),
    ]
