# Generated by Django 4.2.6 on 2024-01-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_organization_is_contragent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='is_contragent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
