# Generated by Django 4.2.6 on 2024-01-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_organization_is_contragent'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='brigade_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='waste',
            name='black_metal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waste',
            name='color_metal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waste',
            name='flex',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waste',
            name='off_color_bottle',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waste',
            name='other',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waste',
            name='paper',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waste',
            name='pss',
            field=models.FloatField(null=True),
        ),
    ]
